version: "3.9"

name: cooperative-guidelines

services:
  postgres:
    image: postgres:16-alpine
    container_name: coop-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cooperative_proposals}
      POSTGRES_USER: ${POSTGRES_USER:-coop}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-coop}
    ports:
      - "5432:5432"
    volumes:
      - coop_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-coop} -d ${POSTGRES_DB:-cooperative}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [coop-net]

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.13.3-management
    container_name: coop-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-coop-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-coop-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - coop_rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [ coop-net ]
volumes:
  coop_pgdata:
  coop_rabbitmq:
networks:
  coop-net:
    driver: bridge
