server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /api/v1
spring:
  application:
    name: CooperativeProposals
  datasource:
    url: ${POSTGRES_DB:jdbc:postgresql://localhost:5432/cooperative_proposals}
    username: ${POSTGRES_USER:coop}
    password: ${POSTGRES_PASSWORD:coop}
  flyway:
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:coop-guest}
    password: ${RABBITMQ_PASSWORD:coop-guest}
springdoc:
  swagger-ui:
    path: /docs
logging:
  level:
    com.miyazaki.cooperativeproposals: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [trace=%X{requestTraceId:-N/A}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [trace=%X{requestTraceId:-N/A}] %logger{36} - %msg%n"


