server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /api/v1
spring:
  application:
    name: CooperativeProposals
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    url: ${POSTGRES_DB:jdbc:postgresql://localhost:5432/cooperative_proposals}
    username: ${POSTGRES_USER:coop}
    password: ${POSTGRES_PASSWORD:coop}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
  flyway:
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:coop-guest}
    password: ${RABBITMQ_PASSWORD:coop-guest}
    connection-timeout: 60000
    template:
      receive-timeout: 10000
      reply-timeout: 10000
springdoc:
  swagger-ui:
    path: /docs
logging:
  level:
    com.miyazaki.cooperativeproposals: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [trace=%X{requestTraceId:-N/A}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [trace=%X{requestTraceId:-N/A}] %logger{36} - %msg%n"

app:
  cpf-validation-enabled: ${CPF_VALIDATION_ENABLED:true}
  base-url: ${APP_BASE_URL:http://localhost:8080}  

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
  cpf-validation:
    url: ${CPF_VALIDATION_URL:https://user-info.herokuapp.com}


